[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.3.0"

[[constraint]]
  name = "github.com/daviddengcn/go-colortext"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
